---
version: '2.0'

default.configure_salt_master:
  tasks:
    apply_config:
      # [105, 332]
      action: salt.client
      input:
        module: state.apply
        matches: "{{ salt_master_id }}"
        args:
          - saltmanage.master
      on-success:
        - clear_cache
    post_notification:
      # [105, 638]
      action: chatops.post_message
      input:
        message: "I reconfigured SaltMaster as requested."
        channel: chatops
    clear_saltcache:
      # [105, 26]
      action: core.local_sudo
      input:
        cmd: "rm -rf /var/cache/salt/master/git*"
      on-success:
        - restart_salt
    restart_saltmaster:
      # [105, 536]
      action: core.local_sudo
      input:
        cmd: "systemctl restart salt-master"
      on-success:
        - post_notification
    restart_salt:
      # [105, 128]
      action: core.local_sudo
      input:
        cmd: "systemctl restart salt-master"
      on-success:
        - wait_for_master
    wait_for_master:
      # [235, 26]
      action: core.pause
      input:
        max_pause: 20
      on-success:
        - refresh_pillar
    refresh_pillar:
      # [105, 230]
      action: salt.client
      input:
        module: saltutil.refresh_pillar
        matches: "{{ salt_master_id }}"
      on-success:
        - apply_config
    clear_cache:
      # [105, 434]
      action: core.local_sudo
      input:
        cmd: "rm -rf /var/cache/salt/master/git*"
      on-success:
        - restart_saltmaster
